# Configuration for Alacritty, the GPU enhanced terminal emulator

# Live config reload (changes require restart)
live_config_reload: true

# Import additional configuration files
#
# Imports are loaded in order, skipping all missing files, with the importing
# file being loaded last. If a field is already present in a previous import, it
# will be replaced.
#
# All imports must either be absolute paths starting with `/`, or paths relative
# to the user's home directory starting with `~/`.
import:
  - ~/.config/alacritty/window.yml
  - ~/.config/alacritty/scrolling.yml
  - ~/.config/alacritty/fonts.yml
  - ~/.config/alacritty/colors.yml
  - ~/.config/alacritty/bell.yml
  - ~/.config/alacritty/key_bindings.yml
  - ~/.config/alacritty/mouse.yml
  - ~/.config/alacritty/cursor.yml
  - ~/.config/alacritty.local/alacritty.yml
#
# vim: nospell
