# Use custom cursor colors. If true, display the cursor in the cursor.foreground
# and cursor.background colors, otherwise invert the colors of the cursor.
# custom_cursor_colors: false

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: false

# TokyoNight Alacritty Colors (storm)
# https://github.com/folke/tokyonight.nvim/blob/main/extras/alacritty_tokyonight_storm.yml
colors:
  # Default colors
  primary:
    background: '0x24283b'
    foreground: '0xc0caf5'

  # Normal colors
  normal:
    black: '0x1D202F'
    red: '0xf7768e'
    green: '0x9ece6a'
    yellow: '0xe0af68'
    blue: '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan: '0x7dcfff'
    white: '0xa9b1d6'

  # Bright colors
  bright:
    black: '0x414868'
    red: '0xf7768e'
    green: '0x9ece6a'
    yellow: '0xe0af68'
    blue: '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan: '0x7dcfff'
    white: '0xc0caf5'

  indexed_colors:
    - { index: 16, color: '0xff9e64' }
    - { index: 17, color: '0xdb4b4b' }
#  # Indexed Colors
#  #
#  # The indexed colors include all colors from 16 to 256.
#  # When these are not set, they're filled with sensible defaults.
#  #
#  # Example:
#  #   `- {index: 16, color: '0xff00ff'}`
#  #
#  indexed_colors: []
