---
name: dotfiles # of the session
root: ~/open_source/dotfiles # of the session
clear_panes: true

windows:
  - editor:
      layout: main-vertical # any valid tmux layout is accepted
      # Short form for panes, with a single command each:
      panes:
        -
        - vim
